import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Menu from './components/Menu.js';
import Footer from './components/Footer.js'
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "SuInstalador",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body className={inter.className}>
        <div>
          <Menu/>
        </div>
        {children}
        <div>
          <Footer/>
        </div>
      </body>
    </html>
  );
}
